package mvc;

import javax.swing.event.CaretListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author Robert
 */
public class RadioMessageView extends FormComponent {

    /**
     * Creates new form RadioMessageView
     */
    public RadioMessageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelMissionNo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMissionNo = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        datePicker = new DateTimePicker();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        jLabel1.setText("CAP RADIO MESSAGE FORM");
        jLabelMissionNo.setText("MISSION NO. :");

        jLabel2.setText("MSG NUMBER *:");

        jLabel3.setText("PRECEDENCE    :");

        jLabel4.setText("DTG                 :");

        jLabel5.setText("FROM              :");

        jLabel6.setText("TO                  :");

        jLabel7.setText("INFO *             :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("SUBJ *            :");

        jLabel9.setText("GROUP CNT *  :");

        jLabel10.setText("BREAK");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel11.setText("BREAK");

        jLabel12.setText("MESSAGE        :");

        jLabel13.setText("MESSAGE RECIEVED");

        jLabel14.setText("FROM  :");

        jLabel15.setText("DTG     :");

        jLabel16.setText("RECIEVING OPERATOR INITIALS :");

        jLabel17.setText("MESSAGE SENT");

        jLabel18.setText("TO   :");

        jLabel19.setText("DTG :");

        jLabel20.setText("SENDING OPERATOR INITIALS :");

        jLabel21.setText("* Optional Field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGap(1,
                                                                                                        1,
                                                                                                        1)
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jLabel5)
                                                                                                                .addComponent(
                                                                                                                        jLabel6)
                                                                                                                .addComponent(
                                                                                                                        jLabelMissionNo)
                                                                                                                .addComponent(
                                                                                                                        jLabel2)
                                                                                                                .addComponent(
                                                                                                                        jLabel4)
                                                                                                                .addComponent(
                                                                                                                        jLabel3)
                                                                                                                .addComponent(
                                                                                                                        jLabel7)
                                                                                                                .addComponent(
                                                                                                                        jLabel8)
                                                                                                                .addComponent(
                                                                                                                        jLabel9)))
                                                                                .addComponent(
                                                                                        jLabel12))
                                                                .addGap(18, 18,
                                                                        18)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(
                                                                                        jTextFieldMissionNo)
                                                                                .addComponent(
                                                                                        jTextField1)
                                                                                .addComponent(
                                                                                        jTextField2)
                                                                                .addComponent(
                                                                                        datePicker)
                                                                                .addComponent(
                                                                                        jTextField4)
                                                                                .addComponent(
                                                                                        jTextField5)
                                                                                .addComponent(
                                                                                        jScrollPane1)
                                                                                .addComponent(
                                                                                        jTextField6)
                                                                                .addComponent(
                                                                                        jTextField7)
                                                                                .addComponent(
                                                                                        jScrollPane2))
                                                                .addGap(12, 12,
                                                                        12))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jLabel10)
                                                                                .addComponent(
                                                                                        jLabel11))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jSeparator4)
                                                                                .addComponent(
                                                                                        jSeparator3)
                                                                                .addComponent(
                                                                                        jSeparator5)
                                                                                .addComponent(
                                                                                        jSeparator6))
                                                                .addContainerGap())
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jLabel13)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jLabel15)
                                                                                                                .addComponent(
                                                                                                                        jLabel14))
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                                .addComponent(
                                                                                                                        jTextField9,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        260,
                                                                                                                        Short.MAX_VALUE)
                                                                                                                .addComponent(
                                                                                                                        jTextField8)))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        jLabel16)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(
                                                                                                        jTextField10,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        116,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        64,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        jLabel20)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(
                                                                                                        jTextField13,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        jLabel18)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(
                                                                                                        jTextField11))
                                                                                .addComponent(
                                                                                        jLabel17)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        jLabel19)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(
                                                                                                        jTextField12)))
                                                                .addContainerGap(
                                                                        98,
                                                                        Short.MAX_VALUE))))
                .addGroup(
                        layout.createSequentialGroup()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(12, 12,
                                                                        12)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jSeparator2)
                                                                                .addComponent(
                                                                                        jSeparator1)))
                                                .addGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addContainerGap(
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(
                                                                        jLabel21)))
                                .addContainerGap()));

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
                new java.awt.Component[] { jTextField10, jTextField13 });

        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel1)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelMissionNo)
                                                .addComponent(
                                                        jTextFieldMissionNo,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(
                                                        jTextField1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(
                                                        jTextField2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4)
                                                .addComponent(
                                                        datePicker,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel5)
                                                .addComponent(
                                                        jTextField4,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(
                                                        jTextField5,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(
                                                        jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(
                                                        jTextField6,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(
                                                        jTextField7,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        jSeparator3,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        10,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        jScrollPane2,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        152,
                                                                        Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jSeparator5,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(
                                                                                        jLabel11))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        jSeparator6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel12))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel17))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel14)
                                                .addComponent(
                                                        jTextField8,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18)
                                                .addComponent(
                                                        jTextField11,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel15)
                                                .addComponent(
                                                        jTextField9,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel19)
                                                .addComponent(
                                                        jTextField12,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel16)
                                                .addComponent(
                                                        jTextField10,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel20)
                                                .addComponent(
                                                        jTextField13,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMissionNo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldMissionNo;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private DateTimePicker datePicker;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;

    // End of variables declaration//GEN-END:variables

    /*
     * The following are functions to be used by the controller to add listeners
     * for changes in fields.
     */

    public void addHeaderMissionNoChangeListener(CaretListener l) {
        jTextFieldMissionNo.addCaretListener(l);
    }

    public void addHeaderMsgNumChangeListener(CaretListener l) {
        jTextField1.addCaretListener(l);
    }

    public void addHeaderPrecedenceChangeListener(CaretListener l) {
        jTextField2.addCaretListener(l);
    }

    public void addHeaderDtgChangeListener(CaretListener l) {
        // datePicker.addCaretListener(l); TODO: NEED LISTENER!!
    }

    public void addHeaderFromChangeListener(CaretListener l) {
        jTextField4.addCaretListener(l);
    }

    public void addHeaderToChangeListener(CaretListener l) {
        jTextField5.addCaretListener(l);
    }

    public void addHeaderInfoChangeListener(CaretListener l) {
        jTextArea1.addCaretListener(l);
    }

    public void addHeaderSubjChangeListener(CaretListener l) {
        jTextField6.addCaretListener(l);
    }

    public void addHeaderGroupCntChangeListener(CaretListener l) {
        jTextField7.addCaretListener(l);
    }

    public void addMessageChangeListener(CaretListener l) {
        jTextArea2.addCaretListener(l);
    }

    public void addMessageRecievedFromChangeListener(CaretListener l) {
        jTextField8.addCaretListener(l);
    }

    public void addMessageRecievedDtgChangeListener(CaretListener l) {
        jTextField9.addCaretListener(l);
    }

    public void addMessageRecievedRecievingOperatorInitialsChangeListener(
            CaretListener l) {
        jTextField10.addCaretListener(l);
    }

    public void addMessageSentToChangeListener(CaretListener l) {
        jTextField11.addCaretListener(l);
    }

    public void addMessageSentDtgChangeListener(CaretListener l) {
        jTextField12.addCaretListener(l);
    }

    public void addMessageSentSendingOperatorInitialsChangeListener(
            CaretListener l) {
        jTextField13.addCaretListener(l);
    }

    public String getHeaderMissionNoText() {
        return jTextFieldMissionNo.getText();
    }

    public String getHeaderMsgNumText() {
        return jTextField1.getText();
    }

    public String getHeaderPrecedenceText() {
        return jTextField2.getText();
    }

    public String getHeaderDtgText() {
        return datePicker.getDateString();
    }

    public String getHeaderFromText() {
        return jTextField4.getText();
    }

    public String getHeaderToText() {
        return jTextField5.getText();
    }

    public String getHeaderInfoText() {
        return jTextArea1.getText();
    }

    public String getHeaderSubjText() {
        return jTextField6.getText();
    }

    public String getHeaderGroupCntText() {
        return jTextField7.getText();
    }

    public String getMessageText() {
        return jTextArea2.getText();
    }

    public String getMessageRecievedFromText() {
        return jTextField8.getText();
    }

    public String getMessageRecievedDtgText() {
        return jTextField9.getText();
    }

    public String getMessageRecievedRecievingOperatorInitialsText() {
        return jTextField10.getText();
    }

    public String getMessageSentToText() {
        return jTextField11.getText();
    }

    public String getMessageSentDtgText() {
        return jTextField12.getText();
    }

    public String getMessageSentSendingOperatorInitialsText() {
        return jTextField13.getText();
    }

    public void setHeaderMissionNoText(String s) {
        jTextFieldMissionNo.setText(s);
    }

    public void setHeaderMsgNumText(String s) {
        jTextField1.setText(s);
    }

    public void setHeaderPrecedenceText(String s) {
        jTextField2.setText(s);
    }

    public void setHeaderDtgText(String s) {
        datePicker.setDate(s);
    }

    public void setHeaderFromText(String s) {
        jTextField4.setText(s);
    }

    public void setHeaderToText(String s) {
        jTextField5.setText(s);
    }

    public void setHeaderInfoText(String s) {
        jTextArea1.setText(s);
    }

    public void setHeaderSubjText(String s) {
        jTextField6.setText(s);
    }

    public void setHeaderGroupCntText(String s) {
        jTextField7.setText(s);
    }

    public void setMessageText(String s) {
        jTextArea2.setText(s);
    }

    public void setMessageRecievedFromText(String s) {
        jTextField8.setText(s);
    }

    public void setMessageRecievedDtgText(String s) {
        jTextField9.setText(s);
    }

    public void setMessageRecievedRecievingOperatorInitialsText(String s) {
        jTextField10.setText(s);
    }

    public void setMessageSentToText(String s) {
        jTextField11.setText(s);
    }

    public void setMessageSentDtgText(String s) {
        jTextField12.setText(s);
    }

    public void setMessageSentSendingOperatorInitialsText(String s) {
        jTextField13.setText(s);
    }
}
